### PR TITLE
Several improvements and general refactoring

### PR DESCRIPTION
**Pull request by daniel-abramov**
Summary:

* Fix the issue with the wrong permissions on files
* Update the Subscriptions API
* Use stronger types for all requests to prevent possibility of errors

### CODE REVIEW

**Comment by dariusc93** [comment]
Any reason for having a stronger type for the request other than to prevent possible errors? The idea of using `serde::Serialize` was to give those who use the library the ability to use their own request types, which in some events like using a older api, or parameters not being supported in this crate for whatever reason.

**Comment by daniel-abramov** [comment]
> Any reason for having a stronger type for the request other than to prevent possible errors? 

I think it was the only reason. I remember when I started to use crate, I did not even know what to pass as arguments actually and I had to either rely on `examples` or constantly checking the Stripe API Reference to compare what it has and to make sure that I properly constructed the parameters. So to make it "safer" I thought that usage of concrete types will make things simpler as the compiler will get the job done.

NB: Actually I think that even the structures for `create()` and `update()` calls should be different, because there are some fields which are **required** for the `create()`, so it makes sense to make them not an `Option<....>`, but rather that concrete type `...`. In case the parameter types for `create()` and `update()` match exactly, the one can create one `XXXParam` structure (like it has been done before) and then just create 2 type aliases (`XXXCreateParam`, `XXXUpdateParam`).

**Comment by dariusc93** [comment]
I do agree that the lack of documentation could leave someone confused and do plan on documenting everything before 0.6, especially since I do have the specs of the API and can properly review everything. I would probably rethink the way data is passed through to the functions, but considering that is a breaking change (to some extent), I would held off on doing that until 0.6. 

Back a couple of years ago, I thought about having a separate struct for handling required parameters, but decided against it since I at the time I wanted to reduce having repeated code since those required parameters can sometimes be reused while updating. Then you have something like `Plans` where some fields are only required if something is set (eg `amount` for Plans is required if `billing_scheme=per_unit`). I guess a non breaking change would probably be to do something like 

```
impl PlansParam {
    pub fn new(currency: Currency, interval: Interval, product: Product) -> PlansParam {
         let mut param = PlansParam::default();
         param.currency = Some(currency);
         param.interval = Some(interval);
         param.product = Some(product);
         param
    }
}
```

Of course its an example but you would get the idea. I think the use of a macro could possibly reduce the need of implementing the functions manually for each resource. I would say we could use procedural macros to mark what fields would be required for what function but that may end up being a breaking change as well.

**Comment by daniel-abramov** [comment]
> but considering that is a breaking change (to some extent), I would held off on doing that until 0.6.

Understood.

I've also recently checked https://github.com/wyyerd/stripe-rs/pull/60 , which seem to contain all things I've tried to add to `libstripe` and the PR seems to be close to be merged. So I'll try to use it after the merge and if `libstripe 0.6` is going to be released after that merge, it could be that my changes won't be that important anymore. Otherwise I'll get back to this PR and try to rebase my changes when `libstripe 0.6` is ready if that makes any sense.

> I guess a non breaking change would probably be to do something like

Agree, that would indeed make the API more convenient.

**Comment by dariusc93** [comment]
Could you revise the PR so that it would have everything except the changes to replace `serde::Serialize`?

**Comment by dariusc93** [comment]
I went on and brought some of this PR into the crate. I will most likely consider on if I should remove `serde::Serialize` in the functions being used, but such changes will likely be done for 0.6.

**Comment by daniel-abramov** [comment]
Ok :)

(I was about to make changes while I received a notification from GitHub that you've just closed it)

**Pull request closed without merging**
