### PR TITLE
Tiered amounts based subscriptions

### PR DESCRIPTION
**Pull request by Aeradriel**
Fixes several things:
- Recursion limit needed to compile on some environment (muslrust based docker for instance)
- `amount` in `Plans` struct can be nil when using tiered amount based subscriptions
- `tiers` should be a `Vec` and some fields are missing in the `Tiers` struct

### CODE REVIEW

**Comment by dariusc93** [comment]
Strange. I tested this crate last week with musl and the couple of examples I built and ran havent required the increase of the recursion limit, though I did use rust-musl-builder and havent tried muslrust, though I assume the process would also be the same there. Was there a specific piece of code you ran where you got an error during compile time?

**Comment by Aeradriel** [comment]
The same code was running fine on my Manjaro setup but required the increase of the recursion limit on my docker image (based on muslrust). By the way, I faced the same issue compiling on my MacOS.

Here is the exact compiler error:

```
error[E0275]: overflow evaluating the requirement `std::option::Option<util::Expandable<resources::core::customer::Customer>>: std::marker::Send`
  --> /Users/thibaut/.cargo/registry/src/github.com-1ecc6299db9ec823/libstripe-0.5.8/src/resources/billing/credit_notes.rs:94:16
   |
94 |         client.post(UrlPath::CreditNote, vec![], param)
   |                ^^^^
```

**Comment by dariusc93** [comment]
I dont own a mac to test to see what is going on, but I am using archlinux (which manjaro is based on) and freebsd without issues. I did test credit notes specifically (will be committing an example soon) as well while expanding the customer field without the error. I am going to accept the PR though but could you provide a sample code or a sample environment where I could reproduce this?

**Comment by terry90** [comment]
@dariusc93 See: https://gist.github.com/terry90/cbb5337335d3252146ef92b62969f83d

**Pull request merged**
